/**
 * Build-time tag index using SQLite (in-memory).
 * Exports a typed module for the app — no SQLite at runtime (Cloudflare-safe).
 */
import { Database } from "bun:sqlite"
import matter from "gray-matter"
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs"
import { basename, join } from "node:path"
import { slugifyTag, tagLabel } from "../src/lib/tags"

const POSTS_DIR = join(import.meta.dir, "../src/content/posts")
const OUT_DIR = join(import.meta.dir, "../src/generated")
const OUT_FILE = join(OUT_DIR, "tag-store.ts")

export function buildTagStore(): void {
  const db = new Database(":memory:")

  db.run(`
    CREATE TABLE tags (
      slug TEXT PRIMARY KEY NOT NULL,
      label TEXT NOT NULL,
      count INTEGER NOT NULL DEFAULT 0
    )
  `)
  db.run(`
    CREATE TABLE post_tags (
      post_slug TEXT NOT NULL,
      tag_slug TEXT NOT NULL,
      PRIMARY KEY (post_slug, tag_slug),
      FOREIGN KEY (tag_slug) REFERENCES tags(slug)
    )
  `)

  const insertTag = db.prepare(
    `INSERT INTO tags (slug, label, count) VALUES (?, ?, 0)
     ON CONFLICT(slug) DO NOTHING`
  )
  const insertPostTag = db.prepare(
    `INSERT OR IGNORE INTO post_tags (post_slug, tag_slug) VALUES (?, ?)`
  )

  const files = readdirSync(POSTS_DIR).filter((f) => f.endsWith(".md"))

  for (const file of files) {
    const postSlug = basename(file, ".md")
    const raw = readFileSync(join(POSTS_DIR, file), "utf8")
    const { data } = matter(raw)
    const rawTags: string[] = Array.isArray(data.tags) ? data.tags : []

    for (const rawTag of rawTags) {
      const slug = slugifyTag(String(rawTag))
      insertTag.run(slug, tagLabel(slug))
      insertPostTag.run(postSlug, slug)
    }
  }

  db.run(`
    UPDATE tags SET count = (
      SELECT COUNT(*) FROM post_tags WHERE post_tags.tag_slug = tags.slug
    )
  `)

  const tags = db
    .query<{ slug: string; label: string; count: number }>(
      `SELECT slug, label, count FROM tags ORDER BY count DESC, slug ASC`
    )
    .all()

  const postTagRows = db
    .query<{ post_slug: string; tag_slug: string }>(
      `SELECT post_slug, tag_slug FROM post_tags ORDER BY tag_slug, post_slug`
    )
    .all()

  const postsByTag: Record<string, string[]> = {}
  for (const row of postTagRows) {
    if (!postsByTag[row.tag_slug]) postsByTag[row.tag_slug] = []
    postsByTag[row.tag_slug]!.push(row.post_slug)
  }

  mkdirSync(OUT_DIR, { recursive: true })

  const source = `// AUTO-GENERATED by scripts/build-tag-store.ts — do not edit
export interface TagRecord {
  slug: string
  label: string
  count: number
  postSlugs: string[]
}

export const tags: TagRecord[] = ${JSON.stringify(
    tags.map((t) => ({
      slug: t.slug,
      label: t.label,
      count: t.count,
      postSlugs: postsByTag[t.slug] ?? [],
    })),
    null,
    2
  )}

export const postsByTag: Record<string, string[]> = ${JSON.stringify(postsByTag, null, 2)}

export const tagSlugs: string[] = ${JSON.stringify(tags.map((t) => t.slug), null, 2)}

export function getTagBySlug(slug: string): TagRecord | undefined {
  return tags.find((t) => t.slug === slug)
}
`

  writeFileSync(OUT_FILE, source, "utf8")
  db.close()
}

if (import.meta.main) {
  buildTagStore()
  console.log(`Wrote ${OUT_FILE}`)
}
